using System.Collections;
using Outblaze;
using UnityEngine;

public class LanguageManager
{
	private Hashtable langData = new Hashtable();

	private UserProfileManager user_obj;

	public LanguageManager()
	{
		user_obj = SingletonMonoBehaviour<InstanceManager>.Instance.UserProfileManagerInstance;
		langData.Add("WeiboSharing", "Do you want to earn # cookies by sharing your acheievement to Weibo?");
		langData.Add("UpgradeScene_Title_Txt", "UPGRADE");
		langData.Add("UpgradeScene_Season_Txt", "STAGE #");
		langData.Add("UpgradeScene_ItemLevel_Txt", "Level #");
		langData.Add("UpgradeScene_MaxLvl_Txt", "MAX");
		langData.Add("UpgradeScene_NotEnoughPoint_Err", "Sorry, you don't have enough Cookies. Do you want to get some?");
		langData.Add("OptionScene_ResetDataConfirmation", "All progress and Cookies earned will be wiped out once you reset. Proceed?");
		langData.Add("InAppsPurchaseSuccess1", "You've just bought ");
		langData.Add("InAppsPurchaseSuccess2", " Cookies!");
		langData.Add("InAppsPurchaseFailed", "Sorry. We're unable to access the Google Play. Please try again later.");
		langData.Add("InAppsPurchaseFailed_Amazon", "Sorry. We're unable to access the Amazon Appstore. Please try again later.");
		langData.Add("NoInternetAccessError", "Please connect to the internet to purchase items.");
		langData.Add("NoInternetAccessError2", "Sorry, internet access is required.");
		langData.Add("NoEventAccessError", "Connection Fail. Please try again later.");
		langData.Add("TapjoyPointReward1", "Congratulations! You have just earned ");
		langData.Add("TapjoyPointReward2", " Cookies!");
		langData.Add("SelectArmyScene_WarriorTitle", "SELECT SPECIAL ATTACK");
		langData.Add("SelectArmyScene_NumenTitle", "SELECT FRIEND");
		langData.Add("SelectArmyScene_NoArmySelectedWarning", "Please select at least one Friend!");
		langData.Add("UpgradeScene_UnlockLevel", "Unlock at stage #");
		langData.Add("UnlockNotification_Title", "Unlocked: ");
		langData.Add("UnlockWeapon1", "Upgrade Garfield's weapon");
		langData.Add("UnlockWeapon2", "Upgrade Garfield's weapon");
		langData.Add("Tutorial0", "Protect the Fridge!");
		langData.Add("Tutorial0b", string.Empty);
		langData.Add("Tutorial1", "Touch the screen");
		langData.Add("Tutorial1b", "to move Garfield left or right");
		langData.Add("Tutorial2", "Garfield attacks automatically");
		langData.Add("Tutorial2b", string.Empty);
		langData.Add("Tutorial3", "Tap the skill button");
		langData.Add("Tutorial3b", "for a powerful attack");
		langData.Add("Tutorial4", "Garfield is hurt!");
		langData.Add("Tutorial4b", "Run left to avoid attacks");
		langData.Add("Tutorial5", "The popcorn machine produces popcorn needed");
		langData.Add("Tutorial5b", "for summoning Friends");
		langData.Add("Tutorial6", "Tap Sheldon to summon him");
		langData.Add("Tutorial6b", string.Empty);
		langData.Add("Tutorial7", "Grab popcorn");
		langData.Add("Tutorial7b", "to summon Friend of choice.");
		langData.Add("Tutorial8", "Grab Cookies to upgrade Troops and Items");
		langData.Add("Tutorial8b", string.Empty);
		langData.Add("Tutorial9", "Upgrade the popcorn machine for faster summoning.");
		langData.Add("Tutorial9b", string.Empty);
		langData.Add("Tutorial10", "Get ready and be on your guard!");
		langData.Add("Tutorial10b", "Enemy forces are incoming!");
		langData.Add("Tutorial11", "This is the enemy bar. The fork moves to the left");
		langData.Add("Tutorial11b", "and the bar decreases everytime an enemy is\ndefeated. Deplete the bar to complete a level.");
		langData.Add("Tutorial12", "A tasty Pie is delivered to you, press the button to restore 100% of Garfield's current Max HP");
		langData.Add("Tutorial12b", string.Empty);
		langData.Add("Tutorial13", "A tasty Pizza is delivered to you, press the button to restore 50% of Garfield's and all friends's current Max HP");
		langData.Add("Tutorial13b", string.Empty);
		langData.Add("Tutorial14", "A cuty Popcorn Box is delivered to you, press the button to restore 30 popcorns to the Popcorn Machine");
		langData.Add("Tutorial14b", string.Empty);
		langData.Add("Tutorial15", "Garfield seems to be more brave to fight, press the button to arm the Garfield for 15 secs invincible");
		langData.Add("Tutorial15b", string.Empty);
		langData.Add("Stage3GenHelp", "You must defend the Fridge. Orson is here to help! You can unlock him at stage 23!");
		langData.Add("InGameStartLevel", "Start of STAGE #");
		langData.Add("SmithLevelUpgrade", "Start at higher popcorn machine level");
		langData.Add("ExtraSpecialAttackSlot", "Buy ONE more skill slot!");
		langData.Add("GoldenArmySlot", "Upgrade friend slot x #");
		langData.Add("GoldenSpecialAttackSlot", "Upgrade special attack slot x #");
		langData.Add("DidUKnow", "Did You Know?");
		langData.Add("GameTips0", "Make sure to upgrade the popcorn machine for faster production. More popcorn means more troops!");
		langData.Add("GameTips1", "Arlene can only spawn one at a time.");
		langData.Add("GameTips2", "Orson can only spawn one at a time.");
		langData.Add("GameTips3", "Dino Odie can only spawn one at a time.");
		langData.Add("GameTips4", "Arlene may not be as strong as Orson and Dino Odie, but she can heal your army in battle.");
		langData.Add("BadGuyDescription4", "Foot Soldiers, the most common Alien Food Invaders, pose little threat to well-trained Friends. They can, however, become a big threat if they attack in large numbers.");
		langData.Add("BadGuyDescription5", "The commander of the alien army, he loves food!!!");
		langData.Add("BadGuyDescription6", "This invader loves to steal popcorn!");
		langData.Add("ShopTitle1", "COOKIES");
		langData.Add("ShopTitle2", "STORE");
		langData.Add("endGameTitle", "CONGRATULATIONS!");
		langData.Add("endGameMsg", "You've cleared all the levels in Garfield Defense. Come back and challenge yourself with a different strategy in the second round!");
		langData.Add("endGameAward", "Awarded:");
		langData.Add("endGameCollected", "Collected:");
		langData.Add("endGameTotal", "Total:");
		langData.Add("DailyGiftNotficiation", "Garfield has a gift for you, come and see what it is!");
		langData.Add("DailyGiftTitle", "Daily Rewards");
		langData.Add("DailyGiftCaption", "Congratulations!");
		langData.Add("DailyGiftMessage", "You've received a special reward for playing multiple days in a row!");
		langData.Add("DailyGiftDayNum", "Day #");
		langData.Add("DailyGift1Name", "# Super Pie");
		langData.Add("DailyGift3Name", "# Special Friends Pizza");
		langData.Add("DailyGift5Name", "# Pop Corn Box");
		langData.Add("DailyGift7Name", "# Garfield's Suit Up Box");
		langData.Add("LoadingTxt", "Loading ....");
		langData.Add("IAP_Cookies", "# Cookies");
		langData.Add("BirthdayTitle", "HAPPY Birthday\nGarfield !!!");
		langData.Add("BirthdayMsg", "It's his 34th birthday and he's giving away these freebies!");
		langData.Add("GiftNo", "Gift");
		langData.Add("BdayGift1Name", "Super Pie x #");
		langData.Add("BdayGift2Name", "Special Friends Pizza x #");
		langData.Add("BdayGift3Name", "Pop Corn Box x #");
		langData.Add("BdayGift4Name", "Garfield's Suit Up Box x #");
		langData.Add("BdayGift5Name", "Cookies x #");
		langData.Add("ChallengeModeUnlocked", "Challenge Mode is unlocked. Explore and have more fun!");
		langData.Add("ChallengeModeNotUnlocked", "Rank up the fun and excitement! Play the Challenge Mode! Unlock the Challenge Mode when you reach Stage 20.");
		langData.Add("NightModeWarning", "Would you like to spend # Cookies to unlock this mode?");
		langData.Add("NightModeResetWarning", "Would you like to proceed with the reset? You wont be able to collect or receive Cookie rewards in this mode again.");
		langData.Add("endGameMsg_ChallengeMode", "You have cleared all the levels in this mode.  Come back and take the challenge again with a different strategy next time!");
		langData.Add("PaidUserAfter20", "The Challenge Mode is now available for FREE!!!\nThis is an exclusive gift for those who have already bought Cookies!");
		langData.Add("PaidUserBefore20", "Get to Stage 20 to play the Challenge Mode for FREE!!!\nThis exclusive offer is available to those who have already bought Cookies!");
		langData.Add("UnpaidUserAfter20", "Challenge Mode is now available!!!");
		langData.Add("UnpaidUserBefore20", "Challenge Mode is available upon reaching Stage 20!");
		langData.Add("ChallengeModeFreeUnlock", "Play the Challenge Mode for FREE by purchasing any Cookie packages.\nWould you like to buy now?");
		langData.Add("videoStr", "Video Offer");
		langData.Add("offerStr", "Other Offer");
		langData.Add("Free", "Free");
		langData.Add("Cookies", "Cookies!");
		langData.Add("zh-Hans_WeiboSharing", "要在Weibo发表你的成就吗? 马上发表就会有#块曲奇送给你");
		langData.Add("zh-Hans_UpgradeScene_Title_Txt", "升级");
		langData.Add("zh-Hans_UpgradeScene_Season_Txt", "第#关");
		langData.Add("zh-Hans_UpgradeScene_ItemLevel_Txt", "第#级");
		langData.Add("zh-Hans_UpgradeScene_MaxLvl_Txt", "最高等级");
		langData.Add("zh-Hans_UpgradeScene_NotEnoughPoint_Err", "对不起! 你的曲奇不够. 想获得更多吗?");
		langData.Add("zh-Hans_OptionScene_ResetDataConfirmation", "所有进度将被清除, 包括已获得的曲奇. 确定要重置吗? ");
		langData.Add("zh-Hans_InAppsPurchaseSuccess1", "成功购买 ");
		langData.Add("zh-Hans_InAppsPurchaseSuccess2", " 块曲奇!");
		langData.Add("zh-Hans_InAppsPurchaseFailed", "抱歉！无法进入Google Play，请稍后再试。");
		langData.Add("zh-Hans_InAppsPurchaseFailed_Amazon", "抱歉！无法进入Google Play，请稍后再试。");
		langData.Add("zh-Hans_NoInternetAccessError", "购物前请先连接互联网。");
		langData.Add("zh-Hans_NoInternetAccessError2", "抱歉！要求联接互联网。");
		langData.Add("zh-Hans_NoEventAccessError", "连接失败. 请稍后再试。");
		langData.Add("zh-Hans_TapjoyPointReward1", "恭喜！刚获得 ");
		langData.Add("zh-Hans_TapjoyPointReward2", " 块曲奇！");
		langData.Add("zh-Hans_SelectArmyScene_WarriorTitle", "选择特殊攻击武器");
		langData.Add("zh-Hans_SelectArmyScene_NumenTitle", "选择队友");
		langData.Add("zh-Hans_SelectArmyScene_NoArmySelectedWarning", "请至少选择一位队友!");
		langData.Add("zh-Hans_UpgradeScene_UnlockLevel", "第#关解锁");
		langData.Add("zh-Hans_UnlockNotification_Title", "已解锁");
		langData.Add("zh-Hans_UnlockWeapon1", "升级加菲猫的武器");
		langData.Add("zh-Hans_UnlockWeapon2", "升级加菲猫的武器");
		langData.Add("zh-Hans_Tutorial0", "必须不惜一切代价保护冰箱！");
		langData.Add("zh-Hans_Tutorial0b", string.Empty);
		langData.Add("zh-Hans_Tutorial1", "触摸屏幕左右移动加菲猫。");
		langData.Add("zh-Hans_Tutorial1b", string.Empty);
		langData.Add("zh-Hans_Tutorial2", "加菲猫会自动攻击屏幕右侧靠近他的那些敌人。");
		langData.Add("zh-Hans_Tutorial2b", string.Empty);
		langData.Add("zh-Hans_Tutorial3", "点击技能按钮, ");
		langData.Add("zh-Hans_Tutorial3b", "发起猛烈还击!");
		langData.Add("zh-Hans_Tutorial4", "加菲猫受到攻击! ");
		langData.Add("zh-Hans_Tutorial4b", "向左跑避开敌人.");
		langData.Add("zh-Hans_Tutorial5", "爆米花机自动生产爆米花可用来召唤护卫们。");
		langData.Add("zh-Hans_Tutorial5b", "还可以捡敌人丢弃的爆米花。集齐足够的爆米花可召唤一个指定的护卫。");
		langData.Add("zh-Hans_Tutorial6", "用5粒爆米花，点选小壳儿可召唤他的增援。");
		langData.Add("zh-Hans_Tutorial6b", string.Empty);
		langData.Add("zh-Hans_Tutorial7", "用爆米花机生产爆米花，");
		langData.Add("zh-Hans_Tutorial7b", "帮你召集队友增援。");
		langData.Add("zh-Hans_Tutorial8", "使用曲奇进行升级。");
		langData.Add("zh-Hans_Tutorial8b", string.Empty);
		langData.Add("zh-Hans_Tutorial9", "升级爆米花机, 加快召集队友的速度！");
		langData.Add("zh-Hans_Tutorial9b", string.Empty);
		langData.Add("zh-Hans_Tutorial10", "做好准备，提高警惕！");
		langData.Add("zh-Hans_Tutorial10b", "敌军来袭！");
		langData.Add("zh-Hans_Tutorial11", "这是敌军状态栏。权杖向左移表示敌军力量削减。");
		langData.Add("zh-Hans_Tutorial11b", "消耗完状态栏内全部军力则完成此游戏关卡。");
		langData.Add("zh-Hans_Tutorial12", "送你一个非常可口的超级馅饼。点击馅饼为加菲猫恢复100％的能量值");
		langData.Add("zh-Hans_Tutorial12b", string.Empty);
		langData.Add("zh-Hans_Tutorial13", "送你一个非常美味的派对比萨。点击比萨为加菲猫和他的全部队友们恢复50％能量值");
		langData.Add("zh-Hans_Tutorial13b", string.Empty);
		langData.Add("zh-Hans_Tutorial14", "补给爆米花到了！点一点它，为爆米花机增加30粒爆米花 ");
		langData.Add("zh-Hans_Tutorial14b", string.Empty);
		langData.Add("zh-Hans_Tutorial15", "加菲猫变得比以往任何时候都勇敢了！点一点帮助加菲猫成为刀枪不入的勇士！");
		langData.Add("zh-Hans_Tutorial15b", string.Empty);
		langData.Add("zh-Hans_Stage3GenHelp", "保护好冰箱，沃森会助你一臂之力！他将在第23关解锁！");
		langData.Add("zh-Hans_InGameStartLevel", "第 # 关开始");
		langData.Add("zh-Hans_SmithLevelUpgrade", "由一个较高等级的爆米花机开始");
		langData.Add("zh-Hans_ExtraSpecialAttackSlot", "装配多一个技能槽！");
		langData.Add("zh-Hans_GoldenArmySlot", "提升军队增援槽 x #");
		langData.Add("zh-Hans_GoldenSpecialAttackSlot", "提升技能槽 x #");
		langData.Add("zh-Hans_DidUKnow", "提示：");
		langData.Add("zh-Hans_GameTips0", "一定要升级爆米花机提高生产力，生产的爆米花越多，可召唤的军队越多。");
		langData.Add("zh-Hans_GameTips1", "一次只能召唤一个阿琳。");
		langData.Add("zh-Hans_GameTips2", "一次只能召唤一个沃森。");
		langData.Add("zh-Hans_GameTips3", "一次只能召唤一个迪諾歐迪");
		langData.Add("zh-Hans_GameTips4", "也许阿琳没有沃森和超级欧迪强状，但她能医治战斗中受伤的战士。");
		langData.Add("zh-Hans_BadGuyDescription4", "步兵，是最常见的外星入侵者，对训练有素的卫士们威协不大，但是，大量的步兵进攻就会造成严重威协。");
		langData.Add("zh-Hans_BadGuyDescription5", "大厨肉丸，这是外星食物入侵者指挥官喜爱的食物!!!");
		langData.Add("zh-Hans_BadGuyDescription6", "小心爆米花");
		langData.Add("zh-Hans_ShopTitle1", "曲奇");
		langData.Add("zh-Hans_ShopTitle2", "商店");
		langData.Add("zh-Hans_endGameTitle", "恭喜！");
		langData.Add("zh-Hans_endGameMsg", "我们的星球很安全！你已成功通过所有加菲猫总动员防御关卡.  再接再厉 , 以不同的策略继续创造更好成绩!");
		langData.Add("zh-Hans_endGameAward", "奖赏：");
		langData.Add("zh-Hans_endGameCollected", "战利品：");
		langData.Add("zh-Hans_endGameTotal", "总计：");
		langData.Add("zh-Hans_DailyGiftNotficiation", "加菲猫有一份礼物送给你，来看看是什么吧！");
		langData.Add("zh-Hans_DailyGiftTitle", "每日奖励");
		langData.Add("zh-Hans_DailyGiftCaption", "恭喜！");
		langData.Add("zh-Hans_DailyGiftMessage", "已收到因连续多天玩此游戏而发放的特别奖赏！");
		langData.Add("zh-Hans_DailyGiftDayNum", "第 # 天");
		langData.Add("zh-Hans_DailyGift1Name", "超级馅饼 x #");
		langData.Add("zh-Hans_DailyGift3Name", "派对比萨 x #");
		langData.Add("zh-Hans_DailyGift5Name", "爆米花筒 x #");
		langData.Add("zh-Hans_DailyGift7Name", "加菲猫无敌盔甲 x #");
		langData.Add("zh-Hans_LoadingTxt", "载入中...");
		langData.Add("zh-Hans_IAP_Cookies", "# 块曲奇");
		langData.Add("zh-Hans_BirthdayTitle", "生日快乐！\n加菲猫！！！");
		langData.Add("zh-Hans_BirthdayMsg", "34年我们一同成长! 真情礼物大派送!");
		langData.Add("zh-Hans_GiftNo", "礼物");
		langData.Add("zh-Hans_BdayGift1Name", "超级馅饼 x #");
		langData.Add("zh-Hans_BdayGift2Name", "派对比萨 x #");
		langData.Add("zh-Hans_BdayGift3Name", "爆米花筒 x #");
		langData.Add("zh-Hans_BdayGift4Name", "加菲猫无敌盔甲 x #");
		langData.Add("zh-Hans_BdayGift5Name", "曲奇 x #");
		langData.Add("zh-Hans_ChallengeModeUnlocked", "解锁了挑战模式。开始探险，乐趣无穷！");
		langData.Add("zh-Hans_ChallengeModeNotUnlocked", "将于第20关解锁挑战模式。请耐心等待！");
		langData.Add("zh-Hans_NightModeWarning", "你想花#曲奇解锁此模式吗？");
		langData.Add("zh-Hans_NightModeResetWarning", "你想进行重置吗？不能再领取或接收该模式中的曲奇奖励。");
		langData.Add("zh-Hans_endGameMsg_ChallengeMode", "您已成功通过此模式的所有关卡。再接再厉, 以不同的策略继续创造更好成绩!");
		langData.Add("zh-Hans_PaidUserAfter20", "现在可免费玩挑战模式！\n此为已购买了曲奇的玩家专享礼物！");
		langData.Add("zh-Hans_PaidUserBefore20", "进入游戏第20关可免费玩挑战模式！\n此为已购买了曲奇的玩家专享礼物！");
		langData.Add("zh-Hans_UnpaidUserAfter20", "现在可玩挑战模式！");
		langData.Add("zh-Hans_UnpaidUserBefore20", "升至第20关可玩挑战模式！");
		langData.Add("zh-Hans_ChallengeModeFreeUnlock", "购买任何曲奇包可免费玩挑战模式，您现在要购买吗？");
		langData.Add("zh-Hans_videoStr", "Video");
		langData.Add("zh-Hans_offerStr", "更多");
		langData.Add("zh-Hans_Free", "免费");
		langData.Add("zh-Hans_Cookies", "曲奇!");
		langData.Add("zh-Hant_WeiboSharing", "要在Weibo發表你的成就嗎? 馬上發表就會有#塊曲奇送給你");
		langData.Add("zh-Hant_UpgradeScene_Title_Txt", "升級");
		langData.Add("zh-Hant_UpgradeScene_Season_Txt", "第#關");
		langData.Add("zh-Hant_UpgradeScene_ItemLevel_Txt", "第#級");
		langData.Add("zh-Hant_UpgradeScene_MaxLvl_Txt", "頂級");
		langData.Add("zh-Hant_UpgradeScene_NotEnoughPoint_Err", "對不起！你的曲奇不夠。你想獲得更多嗎？");
		langData.Add("zh-Hant_OptionScene_ResetDataConfirmation", "所有進度將被清除, 包括已獲得的曲奇. 確定要重置嗎? ");
		langData.Add("zh-Hant_InAppsPurchaseSuccess1", "成功購買 ");
		langData.Add("zh-Hant_InAppsPurchaseSuccess2", " 塊曲奇!");
		langData.Add("zh-Hant_InAppsPurchaseFailed", "抱歉！無法進入Google Play，請稍後再試。");
		langData.Add("zh-Hant_InAppsPurchaseFailed_Amazon", "抱歉！無法進入Google Play，請稍後再試。");
		langData.Add("zh-Hant_NoInternetAccessError", "購物前請先連接互聯網。");
		langData.Add("zh-Hant_NoInternetAccessError2", "抱歉！要求連接互聯網。");
		langData.Add("zh-Hant_NoEventAccessError", "連接失敗。請稍後再試。");
		langData.Add("zh-Hant_TapjoyPointReward1", "恭喜！剛獲得 ");
		langData.Add("zh-Hant_TapjoyPointReward2", " 塊曲奇！");
		langData.Add("zh-Hant_SelectArmyScene_WarriorTitle", "選擇特別攻擊");
		langData.Add("zh-Hant_SelectArmyScene_NumenTitle", "選擇隊友");
		langData.Add("zh-Hant_SelectArmyScene_NoArmySelectedWarning", "請至少選擇一位隊友！");
		langData.Add("zh-Hant_UpgradeScene_UnlockLevel", "第#關解鎖");
		langData.Add("zh-Hant_UnlockNotification_Title", "已解鎖");
		langData.Add("zh-Hant_UnlockWeapon1", "升級加菲貓的武器");
		langData.Add("zh-Hant_UnlockWeapon2", "升級加菲貓的武器");
		langData.Add("zh-Hant_Tutorial0", "必須不惜一切代價保護冰箱！");
		langData.Add("zh-Hant_Tutorial0b", string.Empty);
		langData.Add("zh-Hant_Tutorial1", "觸摸屏幕左右移動加菲貓。");
		langData.Add("zh-Hant_Tutorial1b", string.Empty);
		langData.Add("zh-Hant_Tutorial2", "加菲貓會自動攻擊屏幕右側靠近他的那些敵人。");
		langData.Add("zh-Hant_Tutorial2b", string.Empty);
		langData.Add("zh-Hant_Tutorial3", "點擊技能按鈕, ");
		langData.Add("zh-Hant_Tutorial3b", "發起猛烈還擊!");
		langData.Add("zh-Hant_Tutorial4", "加菲貓受到攻擊！");
		langData.Add("zh-Hant_Tutorial4b", "向左跑避開攻擊。");
		langData.Add("zh-Hant_Tutorial5", "爆穀機自動生產爆穀可用來召喚護衛們。還可以撿敵人丟棄的爆穀。");
		langData.Add("zh-Hant_Tutorial5b", "集齊足夠的爆穀可用來召喚一個指定的護衛。");
		langData.Add("zh-Hant_Tutorial6", "用5粒爆穀，點選小殼兒可召喚他的增援。");
		langData.Add("zh-Hant_Tutorial6b", string.Empty);
		langData.Add("zh-Hant_Tutorial7", "用爆穀機生產爆穀，");
		langData.Add("zh-Hant_Tutorial7b", "幫你召喚朋友的支援。");
		langData.Add("zh-Hant_Tutorial8", "使用曲奇進行升級。");
		langData.Add("zh-Hant_Tutorial8b", string.Empty);
		langData.Add("zh-Hant_Tutorial9", "升級爆穀加快召喚朋友的速度！");
		langData.Add("zh-Hant_Tutorial9b", string.Empty);
		langData.Add("zh-Hant_Tutorial10", "做好準備，提高警惕！");
		langData.Add("zh-Hant_Tutorial10b", "敵軍來襲！");
		langData.Add("zh-Hant_Tutorial11", "這是敵軍狀態欄。權杖向左移表示敵軍力量削減。");
		langData.Add("zh-Hant_Tutorial11b", "消耗完狀態欄內全部軍力則完成此級遊戲。");
		langData.Add("zh-Hant_Tutorial12", "給你一個非常可口的超級餡餅。點點餡餅為加菲貓恢復100％的健康體能");
		langData.Add("zh-Hant_Tutorial12b", string.Empty);
		langData.Add("zh-Hant_Tutorial13", "送你一個非常美味的派對比薩。點點比薩為加菲貓和他的全部朋友們恢復50％健康體能");
		langData.Add("zh-Hant_Tutorial13b", string.Empty);
		langData.Add("zh-Hant_Tutorial14", "補給爆穀到了！點一點它，為爆穀機新增30粒爆穀");
		langData.Add("zh-Hant_Tutorial14b", string.Empty);
		langData.Add("zh-Hant_Tutorial15", "加菲貓變得比以往任何時候都勇敢了！點一點幫助加菲貓成為天下無敵！");
		langData.Add("zh-Hant_Tutorial15b", string.Empty);
		langData.Add("zh-Hant_Stage3GenHelp", "保護好冰箱，沃森會助你一臂之力！他將在第23關解鎖！");
		langData.Add("zh-Hant_InGameStartLevel", "第 # 關開始");
		langData.Add("zh-Hant_SmithLevelUpgrade", "由一個較高等級的爆穀機開始");
		langData.Add("zh-Hant_ExtraSpecialAttackSlot", "裝配多一個技能槽");
		langData.Add("zh-Hant_GoldenArmySlot", "提升軍隊增援槽 x #");
		langData.Add("zh-Hant_GoldenSpecialAttackSlot", "提升技能槽 x #");
		langData.Add("zh-Hant_DidUKnow", "提示：");
		langData.Add("zh-Hant_GameTips0", "一定要升級爆穀機提高生產力，生產的爆穀越多，可召喚的軍隊越多。");
		langData.Add("zh-Hant_GameTips1", "一次只能召喚一個阿琳。");
		langData.Add("zh-Hant_GameTips2", "一次只能召喚一個沃森。");
		langData.Add("zh-Hant_GameTips3", "一次只能召喚一個超級阿的");
		langData.Add("zh-Hant_GameTips4", "也許阿琳沒有沃森和超級阿的強狀，但她能醫治戰鬥中受傷的戰士。");
		langData.Add("zh-Hant_BadGuyDescription4", "步兵，是最常見的外星入侵者，對訓練有素的衛士們威協不大，但是，大量的步兵進攻就會造成嚴重威協。");
		langData.Add("zh-Hant_BadGuyDescription5", "大廚肉丸，這是外星食物入侵者指揮官喜愛的食物!!!");
		langData.Add("zh-Hant_BadGuyDescription6", "小心爆穀神偷");
		langData.Add("zh-Hant_ShopTitle1", "曲奇");
		langData.Add("zh-Hant_ShopTitle2", "商店");
		langData.Add("zh-Hant_endGameTitle", "恭喜！");
		langData.Add("zh-Hant_endGameMsg", "我們的星球很安全！你已成功通過所有加菲貓總動員防禦關卡.  再接再厲 , 以不同的策略繼續創造更好成績!");
		langData.Add("zh-Hant_endGameAward", "獎賞：");
		langData.Add("zh-Hant_endGameCollected", "戰利品：");
		langData.Add("zh-Hant_endGameTotal", "總計：");
		langData.Add("zh-Hant_DailyGiftNotficiation", "加菲貓有一份禮物送給你，來看看是什麼吧！");
		langData.Add("zh-Hant_DailyGiftTitle", "每日獎賞");
		langData.Add("zh-Hant_DailyGiftCaption", "恭喜！");
		langData.Add("zh-Hant_DailyGiftMessage", "已收到因連續多天玩此遊戲而發放的特別獎賞！");
		langData.Add("zh-Hant_DailyGiftDayNum", "第 # 天");
		langData.Add("zh-Hant_DailyGift1Name", "超級餡餅 x #");
		langData.Add("zh-Hant_DailyGift3Name", "派對比薩 x #");
		langData.Add("zh-Hant_DailyGift5Name", "爆穀筒 x #");
		langData.Add("zh-Hant_DailyGift7Name", "加菲貓無敵盔甲 x #");
		langData.Add("zh-Hant_LoadingTxt", "載入中...");
		langData.Add("zh-Hant_IAP_Cookies", "# 塊曲奇");
		langData.Add("zh-Hant_BirthdayTitle", "生日快樂！\n加菲貓！！！");
		langData.Add("zh-Hant_BirthdayMsg", "34年我們一同成長! 真情禮物大派送!");
		langData.Add("zh-Hant_GiftNo", "禮物");
		langData.Add("zh-Hant_BdayGift1Name", "超級餡餅 x #");
		langData.Add("zh-Hant_BdayGift2Name", "派對比薩 x #");
		langData.Add("zh-Hant_BdayGift3Name", "爆穀筒 x #");
		langData.Add("zh-Hant_BdayGift4Name", "加菲貓無敵盔甲 x #");
		langData.Add("zh-Hant_BdayGift5Name", "曲奇 x #");
		langData.Add("zh-Hant_ChallengeModeUnlocked", "解鎖了挑戰模式。開始探險，樂趣無窮！");
		langData.Add("zh-Hant_ChallengeModeNotUnlocked", "將於第20關解鎖挑戰模式。請耐心等待！");
		langData.Add("zh-Hant_NightModeWarning", "你想花#曲奇解鎖此模式嗎？");
		langData.Add("zh-Hant_NightModeResetWarning", "你想進行重置嗎？不能再領取或接收該模式中的曲奇獎勵。");
		langData.Add("zh-Hant_endGameMsg_ChallengeMode", "您已成功通過此模式的所有關卡。再接再厲, 以不同的策略繼續創造更好成績！");
		langData.Add("zh-Hant_PaidUserAfter20", "現在可免費玩挑戰模式！\n此為已購買了曲奇的玩家專享禮物！");
		langData.Add("zh-Hant_PaidUserBefore20", "進入遊戲第20關可免費玩挑戰模式！\n此為已購買了曲奇的玩家專享禮物！");
		langData.Add("zh-Hant_UnpaidUserAfter20", "現在可玩挑戰模式！");
		langData.Add("zh-Hant_UnpaidUserBefore20", "升至第20關可玩挑戰模式！");
		langData.Add("zh-Hant_ChallengeModeFreeUnlock", "購買任何曲奇包可免費玩挑戰模式，您現在要購買嗎？");
		langData.Add("zh-Hant_videoStr", "Video");
		langData.Add("zh-Hant_offerStr", "更多");
		langData.Add("zh-Hant_Free", "免費");
		langData.Add("zh-Hant_Cookies", "曲奇!");
		langData.Add("ja_WeiboSharing", "Do you want to earn # cookies by sharing your acheievement to Weibo?");
		langData.Add("ja_UpgradeScene_Title_Txt", "アップグレード");
		langData.Add("ja_UpgradeScene_Season_Txt", "ステージ #");
		langData.Add("ja_UpgradeScene_ItemLevel_Txt", "レベル #");
		langData.Add("ja_UpgradeScene_MaxLvl_Txt", "レベルMAX");
		langData.Add("ja_UpgradeScene_NotEnoughPoint_Err", "クッキーが足りません。追加しますか？");
		langData.Add("ja_OptionScene_ResetDataConfirmation", "獲得したクッキーを含めて、全てのデータが削除されます。本当にリセットしますか？");
		langData.Add("ja_InAppsPurchaseSuccess1", "クッキーを");
		langData.Add("ja_InAppsPurchaseSuccess2", " 枚購入しました！");
		langData.Add("ja_InAppsPurchaseFailed", "Googleプレイにアクセスできません。");
		langData.Add("ja_InAppsPurchaseFailed_Amazon", "Amazonプレイにアクセスできません。");
		langData.Add("ja_NoInternetAccessError", "アイテムを購入するには、インターネットに接続してください。");
		langData.Add("ja_NoInternetAccessError2", "申し訳ございませんが、インターネットへの接続が必要です。");
		langData.Add("ja_NoEventAccessError", "Connection Fail。 あとでやり直してください。");
		langData.Add("ja_TapjoyPointReward1", "おめでとう！クッキーを ");
		langData.Add("ja_TapjoyPointReward2", " 枚獲得しました！");
		langData.Add("ja_SelectArmyScene_WarriorTitle", "スキルを選択");
		langData.Add("ja_SelectArmyScene_NumenTitle", "トモダチを選択");
		langData.Add("ja_SelectArmyScene_NoArmySelectedWarning", "一人以上トモダチを選択してください！");
		langData.Add("ja_UpgradeScene_UnlockLevel", "ステージ#でアンロックします");
		langData.Add("ja_UnlockNotification_Title", "アンロックしました ");
		langData.Add("ja_UnlockWeapon1", "ガーフィールドの武器をアップグレードする");
		langData.Add("ja_UnlockWeapon2", "ガーフィールドの武器をアップグレードする");
		langData.Add("ja_Tutorial0", "何としてでも冷蔵庫を守りぬくんだ！");
		langData.Add("ja_Tutorial0b", string.Empty);
		langData.Add("ja_Tutorial1", "画面の左右をタッチすることで");
		langData.Add("ja_Tutorial1b", "ガーフィールドを移動させます。");
		langData.Add("ja_Tutorial2", "ガーフィールドは右側近くにいる敵を自動的に攻撃します。");
		langData.Add("ja_Tutorial2b", string.Empty);
		langData.Add("ja_Tutorial3", "スキルボタンをタップすることで");
		langData.Add("ja_Tutorial3b", "特殊スキルが出せます。");
		langData.Add("ja_Tutorial4", "ガーフィールドがダメージを受けています！");
		langData.Add("ja_Tutorial4b", "今すぐ左に移動して攻撃を回避しよう！");
		langData.Add("ja_Tutorial5", "ポップコーンマシンは味方を召喚するためにポップコーンを生産しています。時々敵からポップコーンがドロップします。友達を召喚するためには指定された数のポップコーンが必要になります。");
		langData.Add("ja_Tutorial5b", string.Empty);
		langData.Add("ja_Tutorial6", "まずはポップコーン５粒を使って、シェルドンを召喚してみよう。");
		langData.Add("ja_Tutorial6b", string.Empty);
		langData.Add("ja_Tutorial7", "ポップコーンマシンを使ってポップコーンを生産し、");
		langData.Add("ja_Tutorial7b", "援軍を召喚しましょう。");
		langData.Add("ja_Tutorial8", "クッキーは味方のアップグレードに必要です。");
		langData.Add("ja_Tutorial8b", string.Empty);
		langData.Add("ja_Tutorial9", "ポップコーンマシーンをアップグレードして、援軍をもっと早く召喚できるよ！");
		langData.Add("ja_Tutorial9b", string.Empty);
		langData.Add("ja_Tutorial10", "敵の攻撃を備えよう！");
		langData.Add("ja_Tutorial10b", "もうすぐ敵はやって来るぞ！！");
		langData.Add("ja_Tutorial11", "これは敵戦力ゲージです。敵戦力ゲージは敵を倒すごとで減っていきます。敵の戦力をゼロにすることでステージクリアになります。");
		langData.Add("ja_Tutorial11b", string.Empty);
		langData.Add("ja_Tutorial12", "とてもおいしいスーパーパイが届きました！タップしてガーフィールドのHPが全回復します。");
		langData.Add("ja_Tutorial12b", string.Empty);
		langData.Add("ja_Tutorial13", "とてもおいしいスペシャルフレンドピザが届きました！タップしてガーフィールドとお友達のHPを50％回復します。");
		langData.Add("ja_Tutorial13b", string.Empty);
		langData.Add("ja_Tutorial14", "ポップコーンのお代わりが届きました！アイテムをタップしてポップコーンマシンに30ポップコーンを追加します。");
		langData.Add("ja_Tutorial14b", string.Empty);
		langData.Add("ja_Tutorial15", "絶好調です！アイテムをタップしガーフィールドが無敵状態になります。");
		langData.Add("ja_Tutorial15b", string.Empty);
		langData.Add("ja_Stage3GenHelp", "あなたは必ず冷蔵庫を守らなきゃいけない。オーソンはあなたを助ける為にやってきました！彼はステージ２３でアンロックできます！");
		langData.Add("ja_InGameStartLevel", "ステージスタート #");
		langData.Add("ja_SmithLevelUpgrade", "ポップコーンマシンをより高いレベルからスタートする");
		langData.Add("ja_ExtraSpecialAttackSlot", "スキルスロットを1個拡張しよう！");
		langData.Add("ja_GoldenArmySlot", "即席トモダチスロット x #");
		langData.Add("ja_GoldenSpecialAttackSlot", "即席スキルスロット x #");
		langData.Add("ja_DidUKnow", "ヒント：");
		langData.Add("ja_GameTips0", "ポップコーンマシンをアップグレードして生産スピードを上げよう！ポップコーンをもっとたくさん作れば、もっとたくさんのトモダチを召喚できるよ。");
		langData.Add("ja_GameTips1", "アーリーンは一回につき一匹しか召喚できないよ。");
		langData.Add("ja_GameTips2", "オーソンは一回につき一匹しか召喚できないよ。");
		langData.Add("ja_GameTips3", "ダイノ・オーディーは一回につき一匹しか召喚できないよ。");
		langData.Add("ja_GameTips4", "アーリーンはオーソンやダイノ・オーディーのように戦えないけど、バトルのときは仲間のライフを回復できるよ。");
		langData.Add("ja_BadGuyDescription4", "フード兵士、ごく普通なエイリアン侵略者です。鍛えられたトモダチにとっては楽勝なんだけど、それでもいっぺんに攻められてきたら危ないよ。");
		langData.Add("ja_BadGuyDescription5", "エイリアン侵略者の親分、ミートボール将軍は食べ物が大好き！");
		langData.Add("ja_BadGuyDescription6", "ポップコーン・ナッパーに気をつけよう！");
		langData.Add("ja_ShopTitle1", "クッキー");
		langData.Add("ja_ShopTitle2", "お店");
		langData.Add("ja_endGameTitle", "おめでとうございます！");
		langData.Add("ja_endGameMsg", "これで地球が平和になりました！ガーフィールドのディフェンスのステージを全てクリアしました！新しい戦術でもう一度挑戦してみよう！");
		langData.Add("ja_endGameAward", "もらった：");
		langData.Add("ja_endGameCollected", "獲得した：");
		langData.Add("ja_endGameTotal", "合計：");
		langData.Add("ja_DailyGiftNotficiation", "ガーフィールドがあなたにプレゼントをくれました。何をくれたか見てみましょう！");
		langData.Add("ja_DailyGiftTitle", "毎日のごほうび");
		langData.Add("ja_DailyGiftCaption", "おめでとうございます！");
		langData.Add("ja_DailyGiftMessage", "一日以上続けてゲームをプレイしたため、特別なごほうびがもらえました！");
		langData.Add("ja_DailyGiftDayNum", "Day #");
		langData.Add("ja_DailyGift1Name", "スーパーパイ x #");
		langData.Add("ja_DailyGift3Name", "スペシャルフレンドピザ x #");
		langData.Add("ja_DailyGift5Name", "ポップコーンボックス x #");
		langData.Add("ja_DailyGift7Name", "ガーフィールドのユニフォーム x #");
		langData.Add("ja_LoadingTxt", "ロード中・・・");
		langData.Add("ja_IAP_Cookies", "# クッキー");
		langData.Add("ja_BirthdayTitle", "ガーフィールド、\nお誕生日おめでとう！！");
		langData.Add("ja_BirthdayMsg", "今年が彼の３４才の誕生日、彼からプレゼントを分けてもらいました！");
		langData.Add("ja_GiftNo", "ギフト");
		langData.Add("ja_BdayGift1Name", "スーパーパイ x #");
		langData.Add("ja_BdayGift2Name", "スペシャルフレンドピザ x #");
		langData.Add("ja_BdayGift3Name", "ポップコーンボックス x #");
		langData.Add("ja_BdayGift4Name", "ガーフィールドのユニフォーム x #");
		langData.Add("ja_BdayGift5Name", "クッキー x #");
		langData.Add("ja_ChallengeModeUnlocked", "チャレンジモードはアンロックしました。楽しんでください！");
		langData.Add("ja_ChallengeModeNotUnlocked", "チャレンジモードはステージ２０からアンロックされます。楽しみに待ってね！");
		langData.Add("ja_NightModeWarning", "クッキー#枚を使ってこのモードをアンロックしますか？");
		langData.Add("ja_NightModeResetWarning", "クリアしたステージの記録が消されます。本当にデータをリセットしますか？");
		langData.Add("ja_endGameMsg_ChallengeMode", "あなたはこのモードのステージを全てクリアしました！新しい戦術でもう一度挑戦してみよう！");
		langData.Add("ja_PaidUserAfter20", "チャレンジモードは無料でアンロックしました！\nクッキーを買ったあなたへのプレゼントだよ！");
		langData.Add("ja_PaidUserBefore20", "ステージ２０でチャレンジモードは無料でアンロックします！\nクッキーを買ったあなたへのプレゼントだよ！");
		langData.Add("ja_UnpaidUserAfter20", "チャレンジモードが追加されました！");
		langData.Add("ja_UnpaidUserBefore20", "チャレンジモードがステージ２０で追加されます！");
		langData.Add("ja_ChallengeModeFreeUnlock", "クッキーを購入してチャレンジモードを遊びますか？");
		langData.Add("ja_videoStr", "ビデオを見る");
		langData.Add("ja_offerStr", "ほかの");
		langData.Add("ja_Free", "無料");
		langData.Add("ja_Cookies", "クッキー!");
		langData.Add("ko_WeiboSharing", "Do you want to earn # cookies by sharing your acheievement to Weibo?");
		langData.Add("ko_UpgradeScene_Title_Txt", "업그레이드");
		langData.Add("ko_UpgradeScene_Season_Txt", "스테이지 #");
		langData.Add("ko_UpgradeScene_ItemLevel_Txt", "레벨 #");
		langData.Add("ko_UpgradeScene_MaxLvl_Txt", "최대치 레벨");
		langData.Add("ko_UpgradeScene_NotEnoughPoint_Err", "죄송하지만 쿠키가 충분하지 않습니다. 쿠키를 얻어시겠습니까?");
		langData.Add("ko_OptionScene_ResetDataConfirmation", "획득한 포인트를 포함한 모든 것들이 삭제됩니다. 정말로 재설정을 하시겠습니까?");
		langData.Add("ko_InAppsPurchaseSuccess1", string.Empty);
		langData.Add("ko_InAppsPurchaseSuccess2", " 쿠키를 구매했습니다!");
		langData.Add("ko_InAppsPurchaseFailed", "죄송하지만 현재는 구글 플레이에 접속할 수 없습니다. 나중에 다시 시도해주세요");
		langData.Add("ko_InAppsPurchaseFailed_Amazon", "죄송하지만 현재는 구글 플레이에 접속할 수 없습니다. 나중에 다시 시도해주세요");
		langData.Add("ko_NoInternetAccessError", "아이템을 구매하시려면 3G망을 확인해주세요");
		langData.Add("ko_NoInternetAccessError2", "Sorry, internet access is required.");
		langData.Add("ko_NoEventAccessError", "Connection Fail. 나중에 다시 시도해주세요.");
		langData.Add("ko_TapjoyPointReward1", "축하합니다! 방금 ");
		langData.Add("ko_TapjoyPointReward2", " 쿠키를 획득하셨습니다!");
		langData.Add("ko_SelectArmyScene_WarriorTitle", "특수 공격 기술 선택");
		langData.Add("ko_SelectArmyScene_NumenTitle", "친구 선택");
		langData.Add("ko_SelectArmyScene_NoArmySelectedWarning", "최소한 한 명의 친구를 선택하세요!");
		langData.Add("ko_UpgradeScene_UnlockLevel", "스테이지 #에서 잠금해제");
		langData.Add("ko_UnlockNotification_Title", "잠금을 해제했습니다");
		langData.Add("ko_UnlockWeapon1", "가필드의 무기 업그레이드");
		langData.Add("ko_UnlockWeapon2", "가필드의 무기 업그레이드");
		langData.Add("ko_Tutorial0", "전력을 다해 냉장고를 보호해야만 합니다!");
		langData.Add("ko_Tutorial0b", string.Empty);
		langData.Add("ko_Tutorial1", "가필드를 좌우로 움직이려면");
		langData.Add("ko_Tutorial1b", "화면을 터치하세요.");
		langData.Add("ko_Tutorial2", "가필드는 화면의 오른쪽 근처에 있는");
		langData.Add("ko_Tutorial2b", "적들을 자동으로 공격하게 됩니다.");
		langData.Add("ko_Tutorial3", "강력한 특수 공격이 필요하면");
		langData.Add("ko_Tutorial3b", "스킬 버튼을 선택하세요!");
		langData.Add("ko_Tutorial4", "가필드가 부상 당했습니다!");
		langData.Add("ko_Tutorial4b", "공격을 피하려면 왼쪽으로 도망치세요.");
		langData.Add("ko_Tutorial5", "친구들을 소환하는데 사용되는 팝콘은 팝콘 머신에서 자동적으로 생성됩니다.");
		langData.Add("ko_Tutorial5b", "또한 적들로부터 팝콘을 얻을수도 있습니다. 특정한 친구들을 소환하려면 팝콘이 많이 필요할테니 충분히 모아 두세요.");
		langData.Add("ko_Tutorial6", "팝콘 5개로 쉘든을 소환할수있습니다. 선택해주세요");
		langData.Add("ko_Tutorial6b", string.Empty);
		langData.Add("ko_Tutorial7", "팝콘 머신은 친구들을 소환할수");
		langData.Add("ko_Tutorial7b", "있는 팝콘을 생성합니다.");
		langData.Add("ko_Tutorial8", "업그레이드를 하려면 쿠키를 사용하세요.");
		langData.Add("ko_Tutorial8b", string.Empty);
		langData.Add("ko_Tutorial9", "친구들을 더 빨리 소환하려면 팝콘 머신을 업그레이드 하세요!");
		langData.Add("ko_Tutorial9b", string.Empty);
		langData.Add("ko_Tutorial10", "준비를 하시고 방어준비를하세요! ");
		langData.Add("ko_Tutorial10b", "적군이 쳐들어오고 있습니다!");
		langData.Add("ko_Tutorial11", "이것은 남아있는 적을 나타냅니다.");
		langData.Add("ko_Tutorial11b", "적을 물리칠 때마다 포크는 왼쪽으로 움직이고 막대는 줄어들게 됩니다. 포크가 끝까지 내려가면 레벨을 통과하게 됩니다.");
		langData.Add("ko_Tutorial12", "맛있는 파이가 배달되었으니, 버튼을 눌러서 가필드의 현재 최대 HP를 100% 복구하세요");
		langData.Add("ko_Tutorial12b", string.Empty);
		langData.Add("ko_Tutorial13", "맛있는 피자가 배달되었으니, 버튼을 눌러서 가필드와 모든 친구들의 현재 최대 HP를 50% 복구하세요");
		langData.Add("ko_Tutorial13b", string.Empty);
		langData.Add("ko_Tutorial14", "깜찍한 팝콘 박스가 배달되었으니, 버튼을 눌러서 팝콘 머신에 30개의 팝콘을 복구하세요");
		langData.Add("ko_Tutorial14b", string.Empty);
		langData.Add("ko_Tutorial15", "가필드가 더욱 용감하게 싸우는 것 같으니, 버튼을 눌러서 15초 동안 가필드를 무장시켜 무적으로 만드세요");
		langData.Add("ko_Tutorial15b", string.Empty);
		langData.Add("ko_Stage3GenHelp", "냉장고를 반드시 지켜야 합니다. 올슨이 도와주러 왔습니다! 올슨은 스테이지 23에서  잠금해제할 수 있습니다!");
		langData.Add("ko_InGameStartLevel", "스테이지의 시작 #");
		langData.Add("ko_SmithLevelUpgrade", "더 높은 팝콘 머신 레벨에서 시작");
		langData.Add("ko_ExtraSpecialAttackSlot", "스킬 슬롯을 업그레이드하면 총 3개의 특별한 스킬 슬롯을 받을 수 있다.");
		langData.Add("ko_GoldenArmySlot", "즉시 병력 증원 버프 x #");
		langData.Add("ko_GoldenSpecialAttackSlot", "즉시 스킬 회복 버프 x #");
		langData.Add("ko_DidUKnow", "힌트:");
		langData.Add("ko_GameTips0", "더 빠르게 생산을 하려면 팝콘 머신을 업그레이드 하세요. 팝콘이 많이 생산될수록 더 많은 친구들을 소환할 수 있답니다.");
		langData.Add("ko_GameTips1", "앨린은 한 번에 한 번씩만 소환될 수 있답니다.");
		langData.Add("ko_GameTips2", "올슨은 한 번에 한 번씩만 소환될 수 있답니다.");
		langData.Add("ko_GameTips3", "다이노 오디는 한 번에 한 번씩만 소환될 수 있답니다.");
		langData.Add("ko_GameTips4", "앨린은 올슨이나 오디처럼 강하진 않지만, 전투에서 부상당한 자들을 치유할 수 있답니다.");
		langData.Add("ko_BadGuyDescription4", "가장 흔한 외계 음식 침략자들인 보병은 가필드와 친구들에게 별 위협이 되지않습니다. 하지만 많은 숫자가 한꺼번에 공격을 할 경우엔 큰 위협이 될 수도 있답니다.");
		langData.Add("ko_BadGuyDescription5", "외계침략자 우두머리인 셰프 미트볼은 음식이라면 모두 좋아한답니다!!!");
		langData.Add("ko_BadGuyDescription6", "팝콘 유괴범을 조심하세요!");
		langData.Add("ko_ShopTitle1", "쿠키");
		langData.Add("ko_ShopTitle2", "상점");
		langData.Add("ko_endGameTitle", "축하합니다! ");
		langData.Add("ko_endGameMsg", "이제 우리 지구가 안전합니다!가필드 대 음식물 약탈자 의 모든 레벨들을 통과했습니다! 다음에는 다른 전략으로 새로운 도전해보세요!");
		langData.Add("ko_endGameAward", "보너스:");
		langData.Add("ko_endGameCollected", "획득:");
		langData.Add("ko_endGameTotal", "합계:");
		langData.Add("ko_DailyGiftNotficiation", "가필드가 드릴 선물이 있답니다. 뭔지 어서 확인해보세요!");
		langData.Add("ko_DailyGiftTitle", "매일의 보너스");
		langData.Add("ko_DailyGiftCaption", "축하합니다!");
		langData.Add("ko_DailyGiftMessage", "여러 날 동안 연속해서 게임을 한 덕에 특별 보너스를 받으셨습니다! ");
		langData.Add("ko_DailyGiftDayNum", "# 일째");
		langData.Add("ko_DailyGift1Name", "# 슈퍼 파이");
		langData.Add("ko_DailyGift3Name", "# 특별한 친구들 파이");
		langData.Add("ko_DailyGift5Name", "# 팝콘 박스");
		langData.Add("ko_DailyGift7Name", "# 가필드의 제복 박스");
		langData.Add("ko_LoadingTxt", "로딩중...");
		langData.Add("ko_IAP_Cookies", "# 쿠키");
		langData.Add("ko_BirthdayTitle", "생일 축하해요, \n가필드!!!");
		langData.Add("ko_BirthdayMsg", "가필드의 34번째 생일을 맞아 아래와 같은 선물을 무료로 드립니다!");
		langData.Add("ko_GiftNo", "선물");
		langData.Add("ko_BdayGift1Name", "# 슈퍼 파이");
		langData.Add("ko_BdayGift2Name", "# 특별한 친구들 파이");
		langData.Add("ko_BdayGift3Name", "# 팝콘 박스");
		langData.Add("ko_BdayGift4Name", "# 가필드의 제복 박스");
		langData.Add("ko_BdayGift5Name", "# 쿠키");
		langData.Add("ko_ChallengeModeUnlocked", "도전 모드의 잠금이 풀렸습니다. 신나게 탐험해보세요!");
		langData.Add("ko_ChallengeModeNotUnlocked", "도전 모드의 잠금이 스테이지 20에서 풀립니다. 조금만 참으세요!");
		langData.Add("ko_NightModeWarning", "본 모드의 잠금 해제를 위해 # 쿠키를 사용하시겠습니까?");
		langData.Add("ko_NightModeResetWarning", "그 동안의 모든 것들이 삭제됩니다. 정말로 재설정 하시겠습니까?");
		langData.Add("ko_endGameMsg_ChallengeMode", "본 모드의 레벨들을 모두 통과하셨습니다. 다음에는 다른 전략으로 다시 도전해보세요!");
		langData.Add("ko_PaidUserAfter20", "이젠 도전 모드를 공짜로 즐기세요!!!\n이미 쿠키를 구매하신 분들께만 드리는 특별 선물입니다!");
		langData.Add("ko_PaidUserBefore20", "스테이지 20에 도달하면 도전 모드를 공짜로 즐기실 수 있답니다!!!\n이미 쿠키를 구매하신 분들께만 드리는 특별 선물입니다!");
		langData.Add("ko_UnpaidUserAfter20", "이제 도전 모드를 즐겨보세요!!!");
		langData.Add("ko_UnpaidUserBefore20", "스테이지 20에 도달하면 도전 모드를 즐기실 수 있답니다!");
		langData.Add("ko_ChallengeModeFreeUnlock", "스테이지 20에 도달하면 도전 모드를 즐기실 수 있답니다!\n공짜로 즐기려면 아무 쿠키 패키지나 구매하세요!!!");
		langData.Add("ko_videoStr", "비디오 보기");
		langData.Add("ko_offerStr", "다른 제안");
		langData.Add("ko_Free", "무료");
		langData.Add("ko_Cookies", "쿠키!");
		langData.Add("fr_WeiboSharing", "Do you want to earn # cookies by sharing your acheievement to Weibo?");
		langData.Add("fr_UpgradeScene_Title_Txt", "MISE À NIVEAU");
		langData.Add("fr_UpgradeScene_Season_Txt", "ETAPE #");
		langData.Add("fr_UpgradeScene_ItemLevel_Txt", "Niveau #");
		langData.Add("fr_UpgradeScene_MaxLvl_Txt", "MAX");
		langData.Add("fr_UpgradeScene_NotEnoughPoint_Err", "Désolé. Vous n'avez pas assez de cookies. En voulez-vous plus?");
		langData.Add("fr_OptionScene_ResetDataConfirmation", "Tous les progrès seront effacés, y compris les points gagnés. Etes-vous sûr de vouloir réinitialiser?");
		langData.Add("fr_InAppsPurchaseSuccess1", "Vous venez d'acheter ");
		langData.Add("fr_InAppsPurchaseSuccess2", " de cookies !");
		langData.Add("fr_InAppsPurchaseFailed", "Désolé, nous ne pouvons pas accéder à Google Play. Veuillez s'il vous plaît réessayer plus tard.");
		langData.Add("fr_InAppsPurchaseFailed_Amazon", "Désolé, nous ne pouvons pas accéder à Google Play. Veuillez s'il vous plaît réessayer plus tard.");
		langData.Add("fr_NoInternetAccessError", "Veuillez s'il vous plaît vous connecter à l'Internet pour acheter des articles.");
		langData.Add("fr_NoInternetAccessError2", "Désolé, il faut un accès Internet.");
		langData.Add("fr_NoEventAccessError", "Echec de la connexion. Veuillez s'il vous plaît réessayer plus tard.");
		langData.Add("fr_TapjoyPointReward1", "Félicitations! Vous venez de gagner ");
		langData.Add("fr_TapjoyPointReward2", " Cookies!");
		langData.Add("fr_SelectArmyScene_WarriorTitle", "CHOISIR Attaque Spéciale");
		langData.Add("fr_SelectArmyScene_NumenTitle", "CHOISIR UN AMI");
		langData.Add("fr_SelectArmyScene_NoArmySelectedWarning", "Veuillez s'il vous plaît choisir au moins un ami!");
		langData.Add("fr_UpgradeScene_UnlockLevel", "Déverrouiller à l'étape #");
		langData.Add("fr_UnlockNotification_Title", "Vous avez débloqué");
		langData.Add("fr_UnlockWeapon1", "Mettre à niveau l'arme de Garfield");
		langData.Add("fr_UnlockWeapon2", "Mettre à niveau l'arme de Garfield");
		langData.Add("fr_Tutorial0", "Vous devez à tout prix défendre le frigo!");
		langData.Add("fr_Tutorial0b", string.Empty);
		langData.Add("fr_Tutorial1", "Touchez l'écran pour bouger");
		langData.Add("fr_Tutorial1b", "Garfield à gauche ou à droite.");
		langData.Add("fr_Tutorial2", "Garfield attaquera automatiquement n'importe quel ennemi proche du côté droit de l'écran.");
		langData.Add("fr_Tutorial2b", string.Empty);
		langData.Add("fr_Tutorial3", "Appuyez sur le bouton de compétence afin de");
		langData.Add("fr_Tutorial3b", "déclencher une attaque puissante spéciale!");
		langData.Add("fr_Tutorial4", "Garfield est blessé!");
		langData.Add("fr_Tutorial4b", "Courrez à gauche pour éviter les attaques.");
		langData.Add("fr_Tutorial5", "La machine à popcorn génère automatiquement du popcorn qui peut être utilisé pour faire appel aux Gardiens. Vous pouvez aussi ramasser du popcorn laissé par vos ennemis. Recueillez suffisamment de popcorn nécessaire pour faire appel à un Gardien spécifique.");
		langData.Add("fr_Tutorial5b", string.Empty);
		langData.Add("fr_Tutorial6", "Utilisez 5 popcorn et tappez sur Sheldon pour faire appel à lui.");
		langData.Add("fr_Tutorial6b", string.Empty);
		langData.Add("fr_Tutorial7", "Utilisez la machine à popcorn pour produire du");
		langData.Add("fr_Tutorial7b", "popcorn qui vous aidera à appeler les troupes plus rapidement.");
		langData.Add("fr_Tutorial8", "Utilisez les cookies pour acheter les mises à niveau.");
		langData.Add("fr_Tutorial8b", string.Empty);
		langData.Add("fr_Tutorial9", "Promouvez la machine à popcorn pour appeler les troupes plus rapidement!");
		langData.Add("fr_Tutorial9b", string.Empty);
		langData.Add("fr_Tutorial10", "Préparez-vous et soyez sur vos gardes!");
		langData.Add("fr_Tutorial10b", "Les forces ennemies se rapprochent!");
		langData.Add("fr_Tutorial11", "Ceci est la barre de statut des ennemis. La baguette se déplacera vers la gauche et la barre va diminuer à chaque fois qu'un ennemi sera vaincu. Réduisez la barre pour terminer le niveau.");
		langData.Add("fr_Tutorial11b", string.Empty);
		langData.Add("fr_Tutorial12", "Une tarte goûteuse vous est livrée, appuyez sur le bouton pour rétablir 100% de Max HP en cours de Garfield");
		langData.Add("fr_Tutorial12b", string.Empty);
		langData.Add("fr_Tutorial13", "Une tarte goûteuse vous est livrée, appuyez sur le bouton pour rétablir 50% de Max HP en cours de Garfield");
		langData.Add("fr_Tutorial13b", string.Empty);
		langData.Add("fr_Tutorial14", "Une boîte de pop-corn cuty vous est livrée, appuyez sur le bouton pour restaurer 30 popcorns à la machine à pop corn");
		langData.Add("fr_Tutorial14b", string.Empty);
		langData.Add("fr_Tutorial15", "Garfield semble être plus courageux de se battre, appuyez sur le bouton pour armer le Garfield pendant 15 secondes invincibles");
		langData.Add("fr_Tutorial15b", string.Empty);
		langData.Add("fr_Stage3GenHelp", "Vous devez défendre le frigo. Orson est là pour vous aider! Vous pouvez le débloquer au niveau 23!");
		langData.Add("fr_InGameStartLevel", "Début de l'étape #");
		langData.Add("fr_SmithLevelUpgrade", "Commencer la machine de popcorn à un plus haut niveau");
		langData.Add("fr_ExtraSpecialAttackSlot", "Achetez encore UN emplacement");
		langData.Add("fr_GoldenArmySlot", "Amateurs de troupes instantanées x #");
		langData.Add("fr_GoldenSpecialAttackSlot", "Amateurs d'expérience instantanée x #");
		langData.Add("fr_DidUKnow", "Astuce: ");
		langData.Add("fr_GameTips0", "Assurez-vous de mettre à niveau la machine à popcorn pour une production plus rapide. Plus vous produirez de popcorn, plus vous pourrez appeler de soldats.");
		langData.Add("fr_GameTips1", "Vous ne pouvez invoqué qu'une seule Arlene à la fois.");
		langData.Add("fr_GameTips2", "Vous ne pouvez invoqué qu'un seul Orson à la fois.");
		langData.Add("fr_GameTips3", "Vous ne pouvez invoqué qu'un seul Dino Odie à la fois.");
		langData.Add("fr_GameTips4", "Arlene peut ne pas être aussi forte qu'Orson et Super Odie, mais elle peut guérir votre armée pendant la bataille.");
		langData.Add("fr_BadGuyDescription4", "Les soldats de pied, les envahisseurs extraterrestres les plus communs, présentent peu de danger pour le Gardiens qui sont bien entrainés. Ils peuvent, toutefois, devenir une grande menace s'ils attaquent en grand nombre.");
		langData.Add("fr_BadGuyDescription5", "Capitaine Boulette de viande, le commandeur des envahisseurs extraterrestres adore la nourriture!!!");
		langData.Add("fr_BadGuyDescription6", "Faites attention aux voleurs de popcorn!");
		langData.Add("fr_ShopTitle1", "Cookies");
		langData.Add("fr_ShopTitle2", "Magasin");
		langData.Add("fr_endGameTitle", "FÉLICITATIONS!");
		langData.Add("fr_endGameMsg", "Notre planète est sauvée! Vous avez terminé tous les niveaux de Garfield vs les envahisseurs alimentaires. Revenez et défiez-vous avec une différente stratégie dans un second tour!");
		langData.Add("fr_endGameAward", "Décerné:");
		langData.Add("fr_endGameCollected", "Recueilli:");
		langData.Add("fr_endGameTotal", "Total:");
		langData.Add("fr_DailyGiftNotficiation", "Garfield a un cadeau pour vous, venez voir ce que c'est!");
		langData.Add("fr_DailyGiftTitle", "Rcompenses quotidiennes");
		langData.Add("fr_DailyGiftCaption", "Félicitations!");
		langData.Add("fr_DailyGiftMessage", "Vous avez reçu des récompenses spéciales pour avoir joué pendant plusieurs jours à la suite! ");
		langData.Add("fr_DailyGiftDayNum", "Day #");
		langData.Add("fr_DailyGift1Name", "Super Tarte x #");
		langData.Add("fr_DailyGift3Name", "Tarte Spéciale Amis x #");
		langData.Add("fr_DailyGift5Name", "Boîte de Pop-corn x #");
		langData.Add("fr_DailyGift7Name", "Boîte Suit Up de Garfield x #");
		langData.Add("fr_LoadingTxt", "Chargement en cours ....");
		langData.Add("fr_IAP_Cookies", "# Cookies");
		langData.Add("fr_BirthdayTitle", "Joyeux Anniversaire Garfield !");
		langData.Add("fr_BirthdayMsg", "Il a 34 ans et pour l'occasion il vous offre ces cadeaux");
		langData.Add("fr_GiftNo", "Cadeau");
		langData.Add("fr_BdayGift1Name", "Super Tarte x #");
		langData.Add("fr_BdayGift2Name", "Tarte Spéciale Amis x #");
		langData.Add("fr_BdayGift3Name", "Boîte de Pop-corn x #");
		langData.Add("fr_BdayGift4Name", "Boîte Suit Up de Garfield x #");
		langData.Add("fr_BdayGift5Name", "Cookies x #");
		langData.Add("fr_ChallengeModeUnlocked", "Le mode challenge est débloqué.... Amusez-vous en explorant !");
		langData.Add("fr_ChallengeModeNotUnlocked", "Le mode challenge sera débloqué au niveau 20.... Encore un peu de patience !");
		langData.Add("fr_NightModeWarning", "Voulez-vous utiliser # Cookies pour débloquer ce mode ?");
		langData.Add("fr_NightModeResetWarning", "Voulez-vous vraiment ré-initialiser ? Vous ne pourrez plus recevoir votre récompense de cookies dans ce mode.");
		langData.Add("fr_endGameMsg_ChallengeMode", "Vous avez passé tous les niveaux de ce mode.  Revenez une prochaine fois et recommencez avex une nouvelle stratégie !");
		langData.Add("fr_PaidUserAfter20", "Mode Challenge disponible GRATUITEMENT !  Offre réservée à ceux qui ont déjà acheté des Cookies !");
		langData.Add("fr_PaidUserBefore20", "Mode Challenge GRATUIT dès le niveau 20!!\nOffre réservée à ceux qui ont déjà acheté des Cookies !");
		langData.Add("fr_UnpaidUserAfter20", "Le mode Challenge est disponible !!!");
		langData.Add("fr_UnpaidUserBefore20", "Mode Challenge disponible à partir du niveau 20!");
		langData.Add("fr_ChallengeModeFreeUnlock", "Achetez un pack de Cookies et jouez au mode Challenge GRATUITEMENT.\nAchetez maintenant ?");
		langData.Add("fr_videoStr", "Offre de vidéo");
		langData.Add("fr_offerStr", "Autre offre");
		langData.Add("fr_Free", "Cookies");
		langData.Add("fr_Cookies", "gratuits!");
		langData.Add("de_WeiboSharing", "Do you want to earn # cookies by sharing your acheievement to Weibo?");
		langData.Add("de_UpgradeScene_Title_Txt", "VERBESSERUNG");
		langData.Add("de_UpgradeScene_Season_Txt", "STUFE #");
		langData.Add("de_UpgradeScene_ItemLevel_Txt", "LEVEL #");
		langData.Add("de_UpgradeScene_MaxLvl_Txt", "MAX");
		langData.Add("de_UpgradeScene_NotEnoughPoint_Err", "Entschuldige, aber Du hast nicht genug Kekse. Willst Du mehr haben?");
		langData.Add("de_OptionScene_ResetDataConfirmation", "Alle Fortschritte werden gelöscht, inklusive aller verdienten Punkte. Bist Du sicher das Du alles zurück setzen willst?");
		langData.Add("de_InAppsPurchaseSuccess1", "YDu hast ");
		langData.Add("de_InAppsPurchaseSuccess2", " Kekse gekauft!");
		langData.Add("de_InAppsPurchaseFailed", "Entschuldigung. Wir können keine Verbindung mit Google Play aufbauen. Bitte versuche es später noch einmal.");
		langData.Add("de_InAppsPurchaseFailed_Amazon", "Entschuldigung. Wir können keine Verbindung mit Google Play aufbauen. Bitte versuche es später noch einmal.");
		langData.Add("de_NoInternetAccessError", "Bitte verbinde Dich mit dem Internet um Gegenstände zu kaufen.");
		langData.Add("de_NoInternetAccessError2", "Sorry, eine Internetverbindung wird benötigt.");
		langData.Add("de_NoEventAccessError", "Keine Verbindung. Bitte versuche es später noch einmal.");
		langData.Add("de_TapjoyPointReward1", "Herzlichen Glückwunsch! Du hast ");
		langData.Add("de_TapjoyPointReward2", " Kekse verdient!");
		langData.Add("de_SelectArmyScene_WarriorTitle", "WÄHLE DIE SPEZIAL ATTACKE AUS");
		langData.Add("de_SelectArmyScene_NumenTitle", "WÄHLE EINEN FREUND AUS");
		langData.Add("de_SelectArmyScene_NoArmySelectedWarning", "Bitte wähle mindestens einen Freund aus!");
		langData.Add("de_UpgradeScene_UnlockLevel", "Freischalten auf Stufe #");
		langData.Add("de_UnlockNotification_Title", "Du hast freigeschaltet");
		langData.Add("de_UnlockWeapon1", "Garfields Waffe verbessern");
		langData.Add("de_UnlockWeapon2", "Garfields Waffe verbessern");
		langData.Add("de_Tutorial0", "Du must den Kühlschrank unter allen Umständen beschützen");
		langData.Add("de_Tutorial0b", string.Empty);
		langData.Add("de_Tutorial1", "Berühre den Bildschirm um");
		langData.Add("de_Tutorial1b", "Garfiled nach links oder rechts zu bewegen");
		langData.Add("de_Tutorial2", "Garfield wird automatisch jede gegnerische Einheit auf der rechten Seite des Bildschirmes angreifen.");
		langData.Add("de_Tutorial2b", string.Empty);
		langData.Add("de_Tutorial3", "Berühre den Fähigkeiten Button,");
		langData.Add("de_Tutorial3b", "um Spezial Attacken auszuführen!");
		langData.Add("de_Tutorial4", "Garfield ist verletzt!");
		langData.Add("de_Tutorial4b", "Renne nach links um Attacken auszuweichen");
		langData.Add("de_Tutorial5", "Die Popcorn Maschine stellt automatisch Popcorn her, welches Beschützer herbei ruft. Du kannst auch Popcorn von besiegten Gegnern erhalten. Sammel soviel Popcorn ein, wie Du kannst");
		langData.Add("de_Tutorial5b", string.Empty);
		langData.Add("de_Tutorial6", "Benutze 5 Popcorn und berühre Sheldon um Ihn herbei zu rufen");
		langData.Add("de_Tutorial6b", string.Empty);
		langData.Add("de_Tutorial7", "Benutze die Popcron Maschine, ");
		langData.Add("de_Tutorial7b", "um Popcorn herzustellen, welches Dir erlaubt Helfertruppen herbei zu rufen");
		langData.Add("de_Tutorial8", "Benutze Kekse um Verbesserungen zu kaufen");
		langData.Add("de_Tutorial8b", string.Empty);
		langData.Add("de_Tutorial9", "Verbessere die Popcorn Maschine, um schneller Truppen herbei rufen zu können");
		langData.Add("de_Tutorial9b", string.Empty);
		langData.Add("de_Tutorial10", "Mach die bereit und und pass auf! ");
		langData.Add("de_Tutorial10b", "Gegner sind auf dem Weg!");
		langData.Add("de_Tutorial11", "Dies ist die Gengner Status Anzeige. Die Anzeige wird kleiner mit jedem bezwungenem Gegner. Versuche die Anzeige komplett abzubauen um den Level abzuschließen. ");
		langData.Add("de_Tutorial11b", string.Empty);
		langData.Add("de_Tutorial12", "Dir wurde ein leckerer Super Pie geliefert, drücke auf den Knopf um 100% von Garfields aktueller HP wiederherzustellen;");
		langData.Add("de_Tutorial12b", string.Empty);
		langData.Add("de_Tutorial13", "Dir wurde ein leckerer Spezialfreunde Pie geliefert, drücke auf den Knopf um 50% von Garfields aktueller HP und der HP all seiner Freunde wiederherzustellen;");
		langData.Add("de_Tutorial13b", string.Empty);
		langData.Add("de_Tutorial14", "Popcorn Nachschub ist da! Tippe auf den Artikel um die Popcornmaschine mit Popcorn nachzufüllen.");
		langData.Add("de_Tutorial14b", string.Empty);
		langData.Add("de_Tutorial15", "Garfield ist mutiger als je zuvor! Tippe auf den Artikel um Garfield unbesiegbar zu machen.");
		langData.Add("de_Tutorial15b", string.Empty);
		langData.Add("de_Stage3GenHelp", "Du must den Kühlschrank beschützen. Orson ist hier um Dir zu helfen! Du kannst Ihn mit Level 23 freischalten");
		langData.Add("de_InGameStartLevel", "Start der Stufe #");
		langData.Add("de_SmithLevelUpgrade", "Starte auf einem höheren Popcorn Maschinen Level");
		langData.Add("de_ExtraSpecialAttackSlot", "Kaufe EINEN weiteren Talentslot.");
		langData.Add("de_GoldenArmySlot", "Schlitz für die goldene Armee x #");
		langData.Add("de_GoldenSpecialAttackSlot", "Schlitz für schnellere Talente x #");
		langData.Add("de_DidUKnow", "Tip:");
		langData.Add("de_GameTips0", "Stelle sicher, daß Du die Popcorn Maschine verbesserst, damit Sie schneller produziert. Je mehr Popcorn produziert wird, je mehr Truppen kannst Du zur Hilfe rufen.");
		langData.Add("de_GameTips1", "Arlene kann nur einmal zur selben Zeit herbei gerufen werden.");
		langData.Add("de_GameTips2", "Orson kann nur einmal zur selben Zeit herbei gerufen werden.");
		langData.Add("de_GameTips3", "Dino Odie kann nur einmal zur selben Zeit herbei gerufen werden.");
		langData.Add("de_GameTips4", "Arlene ist vielleicht nicht so stark wie Orson und Super Odie, aber dafür kann Sie deine Truppen während des Kampfes heilen.");
		langData.Add("de_BadGuyDescription4", "Fuß Soldaten, die verbreiteste Art der Ausserirdischen Essens Eindringlinge, stellen nur eine kleine Gefahr für die gut trainierten Beschützer dar. Sie können allerdings zu einer großen gefahr werden, wenn Sie in einer großen Anzahl angreifen.");
		langData.Add("de_BadGuyDescription5", "Chef Fleischklops, der Kommandant der Ausserirdischen Essens Eindringlinge, liebt Essen!");
		langData.Add("de_BadGuyDescription6", "Pass auf den Popcorn Schnapper auf!");
		langData.Add("de_ShopTitle1", "Kekse");
		langData.Add("de_ShopTitle2", "Shop");
		langData.Add("de_endGameTitle", "Gratulation!");
		langData.Add("de_endGameMsg", "Unser Planet ist nun sicher! Du hast alle Level in Garfiled gegen die Essens Eindringlinge abgeschlossen. Nimm die Herrausforderung an, und versuche es einmal mit einer anderen Strategie in der zweiten Runde!");
		langData.Add("de_endGameAward", "Ausgezeichnet:");
		langData.Add("de_endGameCollected", "Gesammelt:");
		langData.Add("de_endGameTotal", "Gesamt:");
		langData.Add("de_DailyGiftNotficiation", "Garfield hat ein Geschenk für Dich. Komm und sieh nach, was es ist!");
		langData.Add("de_DailyGiftTitle", "Tägliche Belohnungen");
		langData.Add("de_DailyGiftCaption", "Gratulation!");
		langData.Add("de_DailyGiftMessage", "Du hast spezielle Belohnungen für das spielen an mehreren Tagen nacheinander erhalten! ");
		langData.Add("de_DailyGiftDayNum", "Tag #");
		langData.Add("de_DailyGift1Name", "Super Pie x #");
		langData.Add("de_DailyGift3Name", "Spezialfreunde Pie x #");
		langData.Add("de_DailyGift5Name", "Pop Corn Box x #");
		langData.Add("de_DailyGift7Name", "Garfield\u00b4s Schicke Klamottenbox x #");
		langData.Add("de_LoadingTxt", "Lade….");
		langData.Add("de_IAP_Cookies", "# Kekse");
		langData.Add("de_BirthdayTitle", "Alles Gute zum Geburtstag,\nGarfield!!!");
		langData.Add("de_BirthdayMsg", "Es ist sein 34. Geburtstag und zur Feier des Tages gibt es diese Gratis Geschenke !");
		langData.Add("de_GiftNo", "Geschenk");
		langData.Add("de_BdayGift1Name", "Super Pie x #");
		langData.Add("de_BdayGift2Name", "Spezialfreunde Pie x #");
		langData.Add("de_BdayGift3Name", "Pop Corn Box x #");
		langData.Add("de_BdayGift4Name", "Garfield\u00b4s Schicke Klamottenbox x #");
		langData.Add("de_BdayGift5Name", "Kekse x #");
		langData.Add("de_ChallengeModeUnlocked", "Challenge Modus entsperrt. Schau ihn Dir näher an und hab noch viel mehr Spaß!");
		langData.Add("de_ChallengeModeNotUnlocked", "Challenge Modus wird ab Phase 20 entsperrt. Du mußt Dich gedulden!");
		langData.Add("de_NightModeWarning", "Willst Du # Kekse ausgeben, um diesen Modus zu entsperren?");
		langData.Add("de_NightModeResetWarning", "Willst Du mit dem Zurücksetzen fortfahren? Du kannst dann in diesem Modus keine Cookie Belohnungen mehr einsammeln oder empfangen.");
		langData.Add("de_endGameMsg_ChallengeMode", "Du hast alle Levels in diesem Modus geschafft. Komm wieder und nimm die Herausforderung nochmal mit einer anderen Strategie an!");
		langData.Add("de_PaidUserAfter20", "Der Herrausforderungsmodus ist nun KOSTENLOS erhältlich!\nDies ist ein exklusives Geschenk für diejenigen, die bereits Kekse gekauft haben!");
		langData.Add("de_PaidUserBefore20", "Erreiche Stufe 20 um den Herrausforderungsmodus KOSTENLOS zu spielen!\nDieses exklusive Angebot ist für diejenigen erhältlich, die bereits Kekse gekauft haben!");
		langData.Add("de_UnpaidUserAfter20", "Herrausforderungsmodus ist nun verfügbar!!!");
		langData.Add("de_UnpaidUserBefore20", "Herrausforderungsmodus ist verfügbar, sobald Level 20 erreicht wurde!!!");
		langData.Add("de_ChallengeModeFreeUnlock", "Spiele den Herrausforderungsmodus KOSTENLOS, wenn Du irgendein Kekspacket kaufst.\nMöchtest Du jetzt eines kaufen?");
		langData.Add("de_videoStr", "Video-Angebot");
		langData.Add("de_offerStr", "Anderes Angebot");
		langData.Add("de_Free", "Kostenlose");
		langData.Add("de_Cookies", "Kekse!");
		langData.Add("es_WeiboSharing", "Do you want to earn # cookies by sharing your acheievement to Weibo?");
		langData.Add("es_UpgradeScene_Title_Txt", "SUBE DE NIVEL");
		langData.Add("es_UpgradeScene_Season_Txt", "#a ETAPA");
		langData.Add("es_UpgradeScene_ItemLevel_Txt", "Nivel #");
		langData.Add("es_UpgradeScene_MaxLvl_Txt", "MAXIMO");
		langData.Add("es_UpgradeScene_NotEnoughPoint_Err", "Lo siento, no tienes galletas suficientes. ¿Quieres más?");
		langData.Add("es_OptionScene_ResetDataConfirmation", "Todo el progreso será borrado, incluso los puntos ganados.¿Estás seguro de que quieres reiniciar el juego?");
		langData.Add("es_InAppsPurchaseSuccess1", "¡Acabas de comprar ");
		langData.Add("es_InAppsPurchaseSuccess2", " galletas!");
		langData.Add("es_InAppsPurchaseFailed", "Lo siento, no podemos acceder a Google Play. Por favor, inténtalo mas tarde.");
		langData.Add("es_InAppsPurchaseFailed_Amazon", "Lo siento, no podemos acceder a Google Play. Por favor, inténtalo mas tarde.");
		langData.Add("es_NoInternetAccessError", "Por favor, conéctate a Internet para comprar productos.");
		langData.Add("es_NoInternetAccessError2", "Lo sentimos, el acceso a Internet es necesario.");
		langData.Add("es_NoEventAccessError", "Error de conexión. Por favor, inténtalo mas tarde.");
		langData.Add("es_TapjoyPointReward1", "¡Felicidades! ¡Acabas de ganar ");
		langData.Add("es_TapjoyPointReward2", " galletas!");
		langData.Add("es_SelectArmyScene_WarriorTitle", "SELECCIONA ATAQUE ESPECIAL");
		langData.Add("es_SelectArmyScene_NumenTitle", "SELECCIONA AMIGO");
		langData.Add("es_SelectArmyScene_NoArmySelectedWarning", "Por favor, ¡selecciona por lo menos a un amigo!");
		langData.Add("es_UpgradeScene_UnlockLevel", "Desbloquear en el nivel #");
		langData.Add("es_UnlockNotification_Title", "Has desbloqueado");
		langData.Add("es_UnlockWeapon1", "Mejora las armas de Garfield");
		langData.Add("es_UnlockWeapon2", "Mejora las armas de Garfield");
		langData.Add("es_Tutorial0", "¡Debes proteger la nevera a todo coste!");
		langData.Add("es_Tutorial0b", string.Empty);
		langData.Add("es_Tutorial1", "Toca la pantalla para mover a");
		langData.Add("es_Tutorial1b", "Garfield hacia la izquierda o hacia la derecha.");
		langData.Add("es_Tutorial2", "Garfield atacará automáticamente a cualquier enemigo que esté cerca del lado derecho de la pantalla.");
		langData.Add("es_Tutorial2b", string.Empty);
		langData.Add("es_Tutorial3", "¡Toca el boton de habilidad para");
		langData.Add("es_Tutorial3b", " desatar un ataque poderoso especial!");
		langData.Add("es_Tutorial4", "¡Garfield está herido!");
		langData.Add("es_Tutorial4b", "Corre hacia la izquierda para evitar los ataques.");
		langData.Add("es_Tutorial5", "La máquina de palomitas produce palomitas automáticamente para que las puedas usar para armar a tus guardianes. También puedes coger las palomitas que dejan caer los enemigos. Recoge suficientes palomitas para armar a un guardian específico.");
		langData.Add("es_Tutorial5b", string.Empty);
		langData.Add("es_Tutorial6", "Usa 5 palomitas y toca a Sheldon para armarlo.");
		langData.Add("es_Tutorial6b", string.Empty);
		langData.Add("es_Tutorial7", "Utiliza la máquina de palomitas para producir palomitas,");
		langData.Add("es_Tutorial7b", "que te permitirán armar a las tropas.");
		langData.Add("es_Tutorial8", "Usa las galletas para comprar mejorias.");
		langData.Add("es_Tutorial8b", string.Empty);
		langData.Add("es_Tutorial9", "¡Mejora la máquina de hacer palomitas para poder armar a las tropas más rápidamente!");
		langData.Add("es_Tutorial9b", string.Empty);
		langData.Add("es_Tutorial10", "¡Prepárate y mantente en guardia!");
		langData.Add("es_Tutorial10b", "¡Los enemigos están viniendo!");
		langData.Add("es_Tutorial11", "Esta es la barra de estado del enemigo. (debería haber una flecha señalándola). La vara se mueve hacia la izquierda y la barra disminuye cada vez que un enemigo es vencido. Vacia la barra para completar el nivel.");
		langData.Add("es_Tutorial11b", string.Empty);
		langData.Add("es_Tutorial12", "Un Súper Pastel muy sabroso le ha sido entregado para restaurar el 100% de Garfield;");
		langData.Add("es_Tutorial12b", string.Empty);
		langData.Add("es_Tutorial13", "Un Pastel Especial de Amigos muy sabroso le ha sido entregado. Tócalo para restaurar en un 50%  el HP de Garfield y todos sus amigos; ");
		langData.Add("es_Tutorial13b", string.Empty);
		langData.Add("es_Tutorial14", "¡La recarga de Popcorn ha llegado! Toca el ítem para agregar 30 palomitas de maíz a la máquina de Popcorn;");
		langData.Add("es_Tutorial14b", string.Empty);
		langData.Add("es_Tutorial15", "¡Garfield se encuentra más valiente que nunca! Toca en el ítem para hacer a Garfield invencible.");
		langData.Add("es_Tutorial15b", string.Empty);
		langData.Add("es_Stage3GenHelp", "Debes defender la nevera. ¡Orson está aquí para ayudarte! ¡Puedes desbloquearlo en el nivel 23!");
		langData.Add("es_InGameStartLevel", "Inicio de la Etapa #");
		langData.Add("es_SmithLevelUpgrade", "Empieza a un nivel más alto de la máquina de palomitas");
		langData.Add("es_ExtraSpecialAttackSlot", "¡Compra OTRO espacio para habilidades!");
		langData.Add("es_GoldenArmySlot", "Insta-tropa de aficionados x #");
		langData.Add("es_GoldenSpecialAttackSlot", "Insta-habilidades de aficionados x #");
		langData.Add("es_DidUKnow", "Consejo: ");
		langData.Add("es_GameTips0", "Asegúrate de que actualizas la máquina de palomitas para una producción más rápida. Cuantas más palomitas produzcas, más tropas podrás armar.");
		langData.Add("es_GameTips1", "A Arlene solo le puedes armar de uno en uno.");
		langData.Add("es_GameTips2", "A Orson solo le puedes armar de uno en uno.");
		langData.Add("es_GameTips3", " A Dino Odie solo le puedes armar de uno en uno.");
		langData.Add("es_GameTips4", "Puede que Arlene no sea tan fuerte como Orson o Super Odie, pero puede curar a tu tropa en la batalla.");
		langData.Add("es_BadGuyDescription4", "Los Foot Soldiers, que son los Alien Food Invaders más comunes, no son muy peligrosos para los Guardianes bien entrenados. Sin embargo, pueden suponer una amenaza sin atacan en equipo.");
		langData.Add("es_BadGuyDescription5", "Al Chef Meatball, el comandante de los Alien Food Invaders, ¡¡¡le encanta la comida!!!");
		langData.Add("es_BadGuyDescription6", "¡Cuidado con el Popcorn Napper!");
		langData.Add("es_ShopTitle1", "Galletas");
		langData.Add("es_ShopTitle2", "Tienda");
		langData.Add("es_endGameTitle", "¡Felicidades!");
		langData.Add("es_endGameMsg", "¡Nuestro planeta está a salvo!Te has pasado todos los niveles en Garfield contra los Food Invaders. Vuelve y desafíate a ti mismo con una nueva estrategia para la segunda ronda!");
		langData.Add("es_endGameAward", "Aggiudicato:");
		langData.Add("es_endGameCollected", "Raccolto:");
		langData.Add("es_endGameTotal", "Totale:");
		langData.Add("es_DailyGiftNotficiation", "Garfield tiene un regalo para ti, ¡ven para ver que es!");
		langData.Add("es_DailyGiftTitle", "Recompensas Diarias");
		langData.Add("es_DailyGiftCaption", "¡Felicidades!");
		langData.Add("es_DailyGiftMessage", "Has recibido recompensas especiales por haber jugado varios días seguidos! ");
		langData.Add("es_DailyGiftDayNum", "Día #");
		langData.Add("es_DailyGift1Name", "Súper Pastel x #");
		langData.Add("es_DailyGift3Name", "Pastel Especial de Amigos x #");
		langData.Add("es_DailyGift5Name", "Caja de Popcorn x #");
		langData.Add("es_DailyGift7Name", "Caja de ropa de Garfield x #");
		langData.Add("es_LoadingTxt", "Cargando...");
		langData.Add("es_IAP_Cookies", "# Galletas");
		langData.Add("es_BirthdayTitle", "¡¡¡Garfield, Feliz Cumpleaños!!!");
		langData.Add("es_BirthdayMsg", "¡Es su cumpleaños número 34 y está obsequiando estos regalos!");
		langData.Add("es_GiftNo", "Regalo");
		langData.Add("es_BdayGift1Name", "Súper Pastel x #");
		langData.Add("es_BdayGift2Name", "Pastel Especial de Amigos x #");
		langData.Add("es_BdayGift3Name", "Caja de Popcorn x #");
		langData.Add("es_BdayGift4Name", "Caja de ropa de Garfield x #");
		langData.Add("es_BdayGift5Name", "Galletas x #");
		langData.Add("es_ChallengeModeUnlocked", "El modo desafío está desbloqueado. ¡Explora y diviértete aún más!");
		langData.Add("es_ChallengeModeNotUnlocked", "El modo desafío se desbloqueará en el Nivel 20. ¡Sé paciente!");
		langData.Add("es_NightModeWarning", "¿Te gustaría gastar # Galletas para desbloquear este modo?");
		langData.Add("es_NightModeResetWarning", "¿Quieres continuar con el reinicio? No podrás reunir o recibir premios de Galletas de nuevo en este modo.");
		langData.Add("es_endGameMsg_ChallengeMode", "Has pasado todos los niveles en este modo. ¡Vuelve y enfrenta el desafío de nuevo con una estrategia distinta!");
		langData.Add("es_PaidUserAfter20", "¡¡¡El Modo Desafío ahora está disponible GRATIS!!!\n¡Este es un regalo exclusivo para aquellos que ya han comprado Galletas!");
		langData.Add("es_PaidUserBefore20", "¡¡¡Llega a la Etapa 20 para jugar el Modo Desafío GRATIS!!!\n¡Esta oferta exclusiva está disponible para aquellos que ya han comprado Galletas! ");
		langData.Add("es_UnpaidUserAfter20", "¡¡¡El Modo Desafío ahora está disponible!!!");
		langData.Add("es_UnpaidUserBefore20", "¡El Modo Desafío está disponible tras alcanzar la Etapa 20!");
		langData.Add("es_ChallengeModeFreeUnlock", "Juega el Modo Desafío GRATIS por la compra de cualquier paquete de Galletas.");
		langData.Add("es_videoStr", "Oferta de Video");
		langData.Add("es_offerStr", "Otra Oferta");
		langData.Add("es_Free", "Galletas");
		langData.Add("es_Cookies", "Gratis!");
	}

	public string getLangData(string key)
	{
		string langCode = user_obj.getLangCode();
		string text = ((!(langCode != "en")) ? key : (langCode + "_" + key));
		Debug.Log("-----> key: " + text);
		if (langData.ContainsKey(text))
		{
			return langData[text].ToString();
		}
		return string.Empty;
	}
}
