public enum StarStrike_GameState
{
	LEVEL_START = 0,
	IN_GAME = 1,
	LEVEL_COMPLETE = 2,
	GAME_OVER = 3,
	GAME_OVER_ANIMATION = 4,
	GAME_COMPLETED = 5,
	WAITING = 6,
	WAIT_LOAD_JERRY_LOSE = 7,
	WAIT_AFTER_TOM_DESTROYED = 8,
	QUIT = 9,
	TOM_ARMY_WAVE_COMING = 10,
	TOM_HEAVY_COMING = 11,
	METEOR_STRIKE_UNLOCKED = 12,
	JERRY_HEAVY_UNLOCKED = 13,
	ROCKET_PUNCH_UNLOCKED = 14,
	QUIT_CONFIRMED = 15
}
