public enum StarStrike_AttachmentKey
{
	GAME_OBJECT = 0,
	ARMY_UNIT = 1,
	EMP_OBJECT = 2,
	ROCKET_CANNON_OBJECT = 3,
	ROCKET_GLOVE_OBJECT = 4,
	METEOR_SHOWER_OBJECT = 5,
	METEOR_OBJECT = 6,
	SOUND_SOURCE = 7
}
